# Config for working hours ---------------------------
DATE_BEFORE="2024-01-01"

# Working hours before 2024
BEFORE_DATE_WORKING_HOURS_MORNING_START=08:00
BEFORE_DATE_WORKING_HOURS_MORNING_END=12:00
BEFORE_DATE_WORKING_HOURS_AFTERNOON_START=14:00
BEFORE_DATE_WORKING_HOURS_AFTERNOON_END=18:00

# Current working hours at home
CURRENT_HOME_DAYS=(2 4)  # Tuesday and Thursday
CURRENT_HOME_HOURS_MORNING_START=09:30
CURRENT_HOME_HOURS_MORNING_END=14:00
CURRENT_HOME_HOURS_AFTERNOON_START=16:00
CURRENT_HOME_HOURS_AFTERNOON_END=18:30

# Current working hours at office
CURRENT_OFFICE_DAYS=(1 3 5)  # Monday, Wednesday and Friday
CURRENT_OFFICE_HOURS_MORNING_START=9:00
CURRENT_OFFICE_HOURS_MORNING_END=12:00
CURRENT_OFFICE_HOURS_AFTERNOON_START=13:00
CURRENT_OFFICE_HOURS_AFTERNOON_END=17:45