# Config for working hours ---------------------------
# Working hours before 2024
BEFORE_2024_WORKING_HOURS_MORNING_START=8
BEFORE_2024_WORKING_HOURS_MORNING_END=12
BEFORE_2024_WORKING_HOURS_AFTERNOON_START=14
BEFORE_2024_WORKING_HOURS_AFTERNOON_END=18

# Current working hours at home
CURRENT_HOME_DAYS=(2 4)  # Tuesday and Thursday
CURRENT_HOME_HOURS_MORNING_START=9.5
CURRENT_HOME_HOURS_MORNING_END=14
CURRENT_HOME_HOURS_AFTERNOON_START=16
CURRENT_HOME_HOURS_AFTERNOON_END=18.5

# Current working hours at office
CURRENT_OFFICE_DAYS=(1 3 5)  # Monday, Wednesday and Friday
CURRENT_OFFICE_HOURS_MORNING_START=9
CURRENT_OFFICE_HOURS_MORNING_END=12
CURRENT_OFFICE_HOURS_AFTERNOON_START=13
CURRENT_OFFICE_HOURS_AFTERNOON_END=17